import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { Camera, Leaf, Book, History, Settings, Home } from "lucide-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function Navbar() {
  return (
    <nav className="flex justify-between items-center h-16 px-6 bg-white text-gray-800 shadow-sm">
        <div className="flex items-center space-x-2">
          <Leaf className="w-6 h-6 text-green-600" />
          <h1 className="text-xl font-bold">LeafLens</h1>
        </div>
        <div className="flex space-x-1">
          <Button variant="ghost" size="sm" className="text-gray-700 hover:text-gray-900 hover:bg-gray-200">
            <Home className="w-5 h-5" />
          </Button>
          <Button variant="ghost" size="sm" className="text-gray-700 hover:text-gray-900 hover:bg-gray-200">
            <Camera className="w-5 h-5" />
          </Button>
          <Button variant="ghost" size="sm" className="text-gray-700 hover:text-gray-900 hover:bg-gray-200">
            <Leaf className="w-5 h-5" />
          </Button>
          <Button variant="ghost" size="sm" className="text-gray-700 hover:text-gray-900 hover:bg-gray-200">
            <Settings className="w-5 h-5" />
          </Button>
        </div>
      </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
